import { queryClient } from '@/services/query'
import '@/styles/globals.css'
import { QueryClientProvider } from '@tanstack/react-query/build/lib/QueryClientProvider'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Component {...pageProps} />
    </QueryClientProvider>
  )
  
}


